import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'id_ID': {
      'app_name': 'myFina',
      'history_btn': 'Riwayat',
      'report_btn': 'Laporan',
      'conf_btn': 'Konfigurasi',
      'history_title': 'Riwayat Transaksi',
      'create_transaction_title': 'Buat Transaksi',
      'outcome_btn': 'Pengeluaran',
      'income_btn': 'Pemasukan',
      'cancel_btn': 'Batal',
      'save_btn': 'Simpan',
      'back_btn': 'Kembali',
      'name_transaction_form': 'Nama',
      'category_form': 'Kategori',
      'choose_category': 'Pilih Kategori',
      'amount_form': 'Nominal',
      'desc_form': 'Deskripsi',
      'data_add_success': 'Berhasil ditambahkan',
      'data_failed_added': 'Data gagal ditambahkan',
      'name_cant_null'.tr: 'Nama tidak boleh kosong',
      'must_less_1mil': 'Harus kurang dari 1 milyar',
      'amount_cant_null': 'Nominal tidak boleh kosong',
      'category_not_choosed': 'Kategori belum dipilih',
      'data_not_valid': 'Data tidak valid',
      'language_title': 'Bahasa',
      'indonesia_language': 'Bahasa Indonesia',
      'eng_language': 'Bahasa Inggris',
    },
    'en_US': {
      'app_name': 'myFina',
      'history_btn': 'History',
      'report_btn': 'Report',
      'conf_btn': 'Configuration',
      'history_title': 'Transaction History',
      'create_transaction_title': 'Create Transaction',
      'outcome_btn': 'Outcome',
      'income_btn': 'Income',
      'cancel_btn': 'Cancel',
      'save_btn': 'Save',
      'back_btn': 'Back',
      'name_transaction_form': 'Name',
      'category_form': 'Category',
      'choose_category': 'Choose Category',
      'amount_form': 'Amount',
      'desc_form': 'Description',
      'data_add_success': 'Data success added',
      'data_failed_added': 'Data failed added',
      'name_cant_null'.tr: 'Name can\'t be empty',
      'must_less_1mil': 'Must less than 1 milion',
      'amount_cant_null': 'Amount can\'t be empty',
      'category_not_choosed': 'Category not choosen',
      'data_not_valid': 'Data not valid',
      'language_title': 'Language',
      'indonesia_language': 'Bahasa Indonesia',
      'eng_language': 'English',
    }
  };
}