import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'id_ID': {
      'app_name': 'myFina',
      'history_btn': 'Riwayat',
      'report_btn': 'Laporan',
      'conf_btn': 'Konfigurasi',
      'history_title': 'Riwayat Transaksi',
      'create_transaction_title': 'Buat Transaksi',
      'outcome_btn': 'Pengeluaran',
      'income_btn': 'Pemasukan',
      'cancel_btn': 'Batal',
      'save_btn': 'Simpan',
      'back_btn': 'Kembali',
      'logout_btn': 'Keluar',
      'yes_btn': 'Ya',
      'name_transaction_form': 'Nama',
      'category_form': 'Kategori',
      'choose_category': 'Pilih Kategori',
      'amount_form': 'Nominal',
      'desc_form': 'Deskripsi',
      'data_add_success': 'Berhasil ditambahkan',
      'data_failed_added': 'Data gagal ditambahkan',
      'name_cant_null'.tr: 'Nama tidak boleh kosong',
      'must_less_1mil': 'Harus kurang dari 1 milyar',
      'amount_cant_null': 'Nominal tidak boleh kosong',
      'category_not_choosed': 'Kategori belum dipilih',
      'data_not_valid': 'Data tidak valid',
      'report_title': 'Laporan Transaksi.',
      'month': 'Bulan',
      'used': 'Terpakai',
      'from': 'dari',
      'outcome_list': 'Daftar pengeluaran',
      'conf_title': 'Konfigurasi.',
      'category_list': 'Daftar Kategori',
      'set_category_title': 'Atur Kategori.',
      'create_category_title': 'Buat Kategori.',
      'name': 'Nama',
      'language': 'Bahasa',
      'language_title': 'Bahasa',
      'indonesia_language': 'Bahasa Indonesia',
      'eng_language': 'Bahasa Inggris',
      'account_logout': 'Keluar Akun',
      'are_you_sure_logout':'Apakah anda yakin ingin keluar dari akun ini?',
      'jan': 'Januari',
      'feb': 'Februari',
      'mar': 'Maret',
      'apr': 'April',
      'may': 'Mei',
      'jun': 'Juni',
      'jul': 'Juli',
      'aug': 'Agustus',
      'sep': 'September',
      'oct': 'Oktober',
      'nov': 'November',
      'des': 'Desember'
    },
    'en_US': {
      'app_name': 'myFina',
      'history_btn': 'History',
      'report_btn': 'Report',
      'conf_btn': 'Configuration',
      'history_title': 'Transaction History',
      'create_transaction_title': 'Create Transaction',
      'outcome_btn': 'Outcome',
      'income_btn': 'Income',
      'cancel_btn': 'Cancel',
      'save_btn': 'Save',
      'back_btn': 'Back',
      'logout_btn': 'Log Out',
      'yes_btn': 'Yes',
      'name_transaction_form': 'Name',
      'category_form': 'Category',
      'choose_category': 'Choose Category',
      'amount_form': 'Amount',
      'desc_form': 'Description',
      'data_add_success': 'Data success added',
      'data_failed_added': 'Data failed added',
      'name_cant_null'.tr: 'Name can\'t be empty',
      'must_less_1mil': 'Must less than 1 milion',
      'amount_cant_null': 'Amount can\'t be empty',
      'category_not_choosed': 'Category not choosen',
      'data_not_valid': 'Data not valid',
      'report_title': 'Transaction Report.',
      'month': 'Month',
      'used': 'Used',
      'from': 'from',
      'outcome_list': 'Outcome List',
      'conf_title': 'Configuration.',
      'category_list': 'Category List',
      'set_category_title': 'Set Categories.',
      'create_category_title': 'Create Category.',
      'name': 'Name',
      'language': 'Language',
      'language_title': 'Language',
      'indonesia_language': 'Bahasa Indonesia',
      'eng_language': 'English',
      'account_logout': 'Log Out from Account',
      'are_you_sure_logout': 'Are you sure want to log out?',
      'jan': 'January',
      'feb': 'February',
      'mar': 'March',
      'apr': 'April',
      'may': 'May',
      'jun': 'June',
      'jul': 'July',
      'aug': 'August',
      'sep': 'September',
      'oct': 'October',
      'nov': 'November',
      'des': 'Desember'
    }
  };
}